const sampleListings = [
{
title: "Cozy Beachfront Cottage",
description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=60" },
price: 1500,
location: "Malibu",
country: "United States",
},
{
title: "Modern Loft in Downtown",
description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=60" },
price: 1200,
location: "New York City",
country: "United States",
},
{
title: "Mountain Retreat",
description: "Unplug and unwind in this peaceful mountain cabin.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60" },
price: 1000,
location: "Aspen",
country: "United States",
},
{
title: "Historic Villa in Tuscany",
description: "Experience the charm of Tuscany in this beautifully restored villa.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=60" },
price: 2500,
location: "Florence",
country: "Italy",
},
{
title: "Secluded Treehouse Getaway",
description: "Live among the treetops in this unique treehouse retreat.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60" },
price: 800,
location: "Portland",
country: "United States",
},
{
title: "Beachfront Paradise",
description: "Step out of your door onto the sandy beach.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=800&q=60" },
price: 2000,
location: "Cancun",
country: "Mexico",
},
{
title: "Rustic Cabin by the Lake",
description: "Spend your days fishing and kayaking.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60" },
price: 900,
location: "Lake Tahoe",
country: "United States",
},
{
title: "Luxury Penthouse with City Views",
description: "Indulge in luxury living with panoramic city views.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?auto=format&fit=crop&w=800&q=60" },
price: 3500,
location: "Los Angeles",
country: "United States",
},
{
title: "Ski-In/Ski-Out Chalet",
description: "Hit the slopes right from your doorstep.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?auto=format&fit=crop&w=800&q=60" },
price: 3000,
location: "Verbier",
country: "Switzerland",
},
{
title: "Safari Lodge in the Serengeti",
description: "Experience the thrill of the wild.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=800&q=60" },
price: 4000,
location: "Serengeti National Park",
country: "Tanzania",
},
{
title: "Historic Canal House",
description: "Stay in a piece of history in Amsterdam.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60" },
price: 1800,
location: "Amsterdam",
country: "Netherlands",
},
{
title: "Private Island Retreat",
description: "Have an entire island to yourself.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?auto=format&fit=crop&w=800&q=60" },
price: 10000,
location: "Fiji",
country: "Fiji",
},
{
title: "Beachfront Bungalow in Bali",
description: "Relax on the sandy shores of Bali.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?auto=format&fit=crop&w=800&q=60" },
price: 1800,
location: "Bali",
country: "Indonesia",
},
{
title: "Art Deco Apartment in Miami",
description: "Step into the glamour of the 1920s.",
image: { filename: "listingimage", url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?auto=format&fit=crop&w=800&q=60" },
price: 1600,
location: "Miami",
country: "United States",
},
{
title: "Tropical Villa in Phuket",
description: "Escape to a tropical paradise.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?auto=format&fit=crop&w=800&q=60" },
price: 3000,
location: "Phuket",
country: "Thailand",
},
{
title: "Desert Oasis in Dubai",
description: "Experience luxury in the desert.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=800&q=60" },
price: 5000,
location: "Dubai",
country: "United Arab Emirates",
},
{
title: "Modern Apartment in Tokyo",
description: "Explore the vibrant city of Tokyo.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?auto=format&fit=crop&w=800&q=60" },
price: 2000,
location: "Tokyo",
country: "Japan",
},
{
title: "Luxury Villa in the Maldives",
description: "Indulge in luxury in this overwater villa.",
image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=800&q=60" },
price: 6000,
location: "Maldives",
country: "Maldives",
}
];

module.exports = { data: sampleListings };